backend:
  name: test-repo

media_folder: "images"
public_folder: "/images"

collections:
  - name: "werke"
    label: "Galerie – Keramikstücke"
    folder: "content/werke"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Beschreibung", name: "description", widget: "text" }
      - { label: "Bild", name: "image", widget: "image" }
